name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/checkout@v3
        with:
          path: data
          ref: data
        continue-on-error: true
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.25"
      - run: bun install
      - run: bun run ./build.ts
        env:
          NODE_ENV: production
          VITE_GIALOG_BASE_URL: https://yuheinakasaka.github.io/gialog-diary
          VITE_GIALOG_PUBLIC_STATIC_URL: https://yuheinakasaka.github.io/gialog-diary
          VITE_BASE_PATH: /gialog-diary
          VITE_BLOG_TITLE: Yuhei Nakasaka's Blog
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: static
